### ISSUE TITLE
failed installation of already installed packages

### ISSUE THREAD

**Issue by bjoerntorben** [MoonLiightz/dotfiles#10]
### System information

OS: macOS Ventura 13.2
arch: arm64
Package Manager: Homebrew 3.6.20
zsh: 5.9 (arm-apple--darwin-22.1.0)

### Bug description

Failed to install brew package, because it is already installed.

### Steps to reproduce

1. Install alfred app via dmg file
2. run ./boostrap.sh all
3. Anwser all questions with 'Y'

### Expected behavior

check if package is already installed and skip installation or ask the user to remove it and install it with brew.

**Comment by MoonLiightz** [comment]
I think that is how Brew works. For me, this is okay, because I do not install things like Alfred manually, just through the homebrew bundle file. In other cases you should see for yourself what the most suitable way is.  
Unfortunately, there is no option for brew bundle to ignore or skip already installed casks, at least none that I know of. Otherwise I would be willing to include them in the script. But currently, this is not an issue for me.
